{% set name = "csdms-dakotathon" %}
{% set version = "0.3.1" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/dakota

build:
  number: 0

requirements:
  build:
    - babelizer
    - dakotathon
  run:
    - cca-tools
    - dakotathon

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model:Dakotathon
  license: MIT
  summary: Dakotathon is a Python wrapper for the Dakota systems analysis toolkit.
  dev_url: https://github.com/csdms/dakota
