{% set name = "csdms-dakotathon" %}
{% set version = "0.3" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/dakota

requirements:
  build:
    - bmi-babel
    - dakotathon
  run:
    - bmi-babel
    - dakotathon

test:
  requires:
    - pymt
    - bmi-tester
